/*
This file is imported by `src/bin/make_data.js`
- we can't import files generated by it like `data/datasets.json` in here
- we can't import @svizzle/ui as its index exports `.svelte` files
*/

import {isClientSide} from '@svizzle/ui';

let lastId = 0;
export function autoID () {
	return `${isClientSide ? 'client' : 'server'}${lastId++}`;
}
