/*
This file is imported by `src/bin/make_data.js`
- we can't import files generated by it like `data/datasets.json` in here
- we can't import @svizzle/ui as its index exports `.svelte` files
*/

import {
	isObject,
	isString,
	makePostfixed,
	applyFnMap
} from '@svizzle/utils';
import * as _ from 'lamb';

import {useCache, selectedCacheURL} from '$lib/env.js';

export const getSource = _.getKey('source');
export const getSpecVersion = _.getKey('version');
export const getApiVersion = _.getPath('spec.dataset.api_version');
export const getSchema = _.getPath('spec.dataset.schema');
export const getEsEndpointURL = _.getPath('spec.dataset.endpoint_url');
export const getEsSearchURL = _.pipe([getEsEndpointURL, makePostfixed('/_search')]);
export const getBeEndpointURL = useCache
// FIXME import `es` from shared configuration with BE
	? spec => `${selectedCacheURL}/es/${_.getPathIn(spec, 'spec.dataset.endpoint_url')}`
	: getEsEndpointURL;
export const getBeCoverageEndpointURL = spec =>
	`${selectedCacheURL}/coverage/${_.getPathIn(spec, 'spec.dataset.endpoint_url')}`
export const getBeSearchURL = _.pipe([getBeEndpointURL, makePostfixed('/_search')]);
export const getFieldTypeId = _.getKey('type');
export const getESType = _.adapter([
	_.casus(isObject, getFieldTypeId),
	_.casus(isString, _.identity),
	_.always('unknown')
]);

export const getDocCount = _.getKey('doc_count');
export const getLocation = _.getKey('location');

// e.g. `arxlive_arxiv_v3`
export const getDatasetIdOf =
	({project, source, version}) => `${project}_${source}_v${version}`;

export const groupBySource = _.groupBy(getSource);

export const makeDatasetBySource = _.pipe([
	_.groupBy(getSource),
	_.mapValuesWith(_.sortWith([_.getKey('project'), getSpecVersion])),
	_.values,
	_.sortWith([getSource]),
	_.mapWith(applyFnMap({
		source: _.getPath('0.source'),
		releases: _.sortWith([getSpecVersion])
	}))
]);
