root: true
extends:
- '../.eslintrc.yml'
- 'plugin:svelte/base'
rules:
  node/no-missing-import: off
  node/no-extraneous-import: off
#  import/extensions:
#    - error
#    - always
settings:
  import/parsers:
    svelte-eslint-parser:
    - '.svelte'
    '@babel/eslint-parser':
    - '.js'
  import/resolver:
    eslint-import-resolver-custom-alias:
      alias:
        '$lib': './src/lib'
      extensions:
      - '.js'
overrides:
- files:
  - '**/*.svelte'
  rules:
    svelte/html-closing-bracket-spacing: error
    svelte/html-quotes:
    - error
    - prefer: single
    svelte/indent:
    - off
    - indent: tab
    svelte/no-at-debug-tags: warn
    svelte/no-at-html-tags: off
    svelte/no-dupe-else-if-blocks: error
    svelte/no-dupe-style-properties: error
    svelte/no-dynamic-slot-name: error
    svelte/no-inner-declarations: error
    svelte/no-not-function-handler: error
    svelte/no-object-in-text-mustaches: error
    svelte/no-shorthand-style-property-overrides: error
    svelte/no-unknown-style-directive-property: warn
    svelte/no-unused-svelte-ignore: warn
    brace-style: off
    import/no-unresolved: off
    no-invalid-this: off
    no-new: off
    no-shadow: off
    no-self-assign: off
- files:
  - '**/*.spec.js'
  env:
    mocha: true
